### ISSUE TITLE
bipfont.py unpack is not working

### ISSUE THREAD

**Issue by Stefan1200-de** [amazfitbip/tools#59]
I tried to unpack different amazfit font files, but bipfont.py use an unsupported operand: 

`bipfont.py unpack ISOCPEUR.ft
('Unpacking', 'ISOCPEUR.ft')
Traceback (most recent call last):
  File "D:\Downloads\Amazfit Bip\AmazfitBip-tools-master\bipfont.py", line 148, in <module>
    unpackFont(sys.argv[2])
  File "D:\Downloads\Amazfit Bip\AmazfitBip-tools-master\bipfont.py", line 33, in unpackFont
    num_ranges = (header[0x21] << 8) + header[0x20]
TypeError: unsupported operand type(s) for <<: 'str' and 'int'`

Using Python 2.7, Pillow 5.3.0 and the newest pathlib library for AMD64 on Windows 10. What can I do here to fix this issue?

**Update:** The amazfitbip tools readme told me that Python 2.7 is required. But it is not working. It seems that Python 3+ is required, because with Python 3.6.6 it is working. So the only issue here is updating the system requirements in the readme file.

**Comment by rysson** [comment]
Yes, script reads ranges (eg. 253) and use the only last one. There is really something wrong.
